/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Codigos;

import static Codigos.Arquivo.palavras_separadas_linha_1;
import static Codigos.Arquivo.palavras_separadas_linha_2;
import static Codigos.Arquivo.palavras_separadas_linha_3;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Ibyte
 */
public class Tela extends javax.swing.JFrame {
    
    public int vez;
    public int total_de_atendimentos;
    public int atendimentos_tec_1;
    public int atendimentos_tec_2;
    public int atendimentos_tec_3;
    public int contador;
    public int hora_chegada_tec_1 = 10;
    public int hora_chegada_tec_2 = 8;
    public int hora_chegada_tec_3 = 8;
    public int hora_saida_tec_1 = 19;
    public int hora_saida_tec_2 = 17;
    public int hora_saida_tec_3 = 17;
    public int minuto_saida_tec_1 = 30;
    public int minuto_saida_tec_2 = 0;
    public int minuto_saida_tec_3 = 0;
    public int minuto_chegada_tec_1 = 20;
    public int minuto_chegada_tec_2 = 0;
    public int minuto_chegada_tec_3 = 0;
    public String entrada_tec_1 = "10:20:00";
    public String entrada_tec_2 = "08:00:00";
    public String entrada_tec_3 = "08:00:00";
    public String saida_tec_1 = "19:30:00";
    public String saida_tec_2 = "17:00:00";
    public String saida_tec_3 = "17:00:00";
    
    
    
    
    public int hora, minuto, segundo;
    public String horas;
    public Calendar now;
    public Color red = Color.red;
    public Color black = Color.BLACK;
    public Timer timer;
    public Boolean ativar = false;//FALSE == ATIVADO
    public Boolean desativar = true;//TRUE == DESATIVADO
    
    public Password password;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }
    
    public void obterHoras(){
        now = Calendar.getInstance();
        horas = String.format("%1$tH:%1$tM:%1$tS", now);//HORAS NO FORMATO 13:00:00
        hora = Integer.parseInt(String.format("%1$tH", now));//HORAS 13
        minuto = Integer.parseInt(String.format("%1$tM", now));//MINUTO 00
        segundo = Integer.parseInt(String.format("%1$tS", now));//SEGUNDO
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TEXTO_NOME_DA_VEZ = new javax.swing.JLabel();
        BOTAO_ZERAR = new javax.swing.JButton();
        TEXTO_TOTAL = new javax.swing.JLabel();
        TEC_1_BTN = new javax.swing.JToggleButton();
        TEC_2_BTN = new javax.swing.JToggleButton();
        TEC_3_BTN = new javax.swing.JToggleButton();
        TEXTO_HORA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TEXTO_NOME_DA_VEZ.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        TEXTO_NOME_DA_VEZ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        BOTAO_ZERAR.setText("Zerar");
        BOTAO_ZERAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_ZERARActionPerformed(evt);
            }
        });

        TEXTO_TOTAL.setText("Atendimentos : ");

        TEC_1_BTN.setText("Técnico 1");
        TEC_1_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TEC_1_BTNMouseClicked(evt);
            }
        });

        TEC_2_BTN.setText("Técnico 2");
        TEC_2_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TEC_2_BTNMouseClicked(evt);
            }
        });

        TEC_3_BTN.setText("Técnico 3");
        TEC_3_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TEC_3_BTNMouseClicked(evt);
            }
        });

        TEXTO_HORA.setText("00:00:00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TEXTO_NOME_DA_VEZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(TEC_1_BTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TEC_2_BTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TEC_3_BTN)
                        .addGap(0, 95, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(BOTAO_ZERAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TEXTO_TOTAL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TEXTO_HORA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOTAO_ZERAR)
                    .addComponent(TEXTO_TOTAL)
                    .addComponent(TEXTO_HORA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(TEXTO_NOME_DA_VEZ, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEC_1_BTN)
                    .addComponent(TEC_2_BTN)
                    .addComponent(TEC_3_BTN))
                .addGap(66, 66, 66))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        password = new Password();
        obterHoras();//OBTEM A HORA EM QUE O PROGRAMA É ABERTO
        Codigos.Pasta.criar("GaF02");//Cria a pasta principal do programa C:\\GaF02
        Codigos.Arquivo.criar("Tecnicos");//Cria o arquivo principal do programa C:\\GaF02\\Tecnicos.txt
        Codigos.Arquivo.criar("Registros");//Cria o arquivo C:\\GaF02\\Registros.txt
        Codigos.Arquivo.ler("Tecnicos");//Faz a leitura do arquivo principal C:\\GaF02\\Tecnicos.txt
        
        BOTAO_ZERAR.setEnabled(false);//INICIA COM O BOTAO ZERAR DESATIVADO
        TEXTO_NOME_DA_VEZ.setForeground(black);//DEFINE A COR PADRAO
        
        ////////////////////////////////////////////////////////////////////////
        /*INICIA COM O TECNICO 1 DESABILITADO*/
        TEC_1_BTN.setText(""+palavras_separadas_linha_1[0]);
        TEC_1_BTN.setEnabled(false);
        ////////////////////////////////////////////////////////////////////////
        
        timer = new Timer(1000, (ActionEvent e) -> {
            
            contador++;
            
            obterHoras();

            TEXTO_HORA.setText(horas);
            ////////////////////////////////////////////////////////////////////
            /*HABILITA O BOTAO NA HORA E MINUTO DEFINIDOS*/
            if(horas.equals(entrada_tec_1)){
                TEC_1_BTN.setEnabled(true);
                TEC_1_BTN.setSelected(ativar);
                TEC_1_BTN.setBackground(Color.green);
            }
            if(horas.equals(entrada_tec_2)){
                TEC_2_BTN.setSelected(ativar);
                TEC_2_BTN.setBackground(Color.green);
            }
            if(horas.equals(entrada_tec_3)){
                TEC_3_BTN.setSelected(ativar);
                TEC_3_BTN.setBackground(Color.green);
            }
            ////////////////////////////////////////////////////////////////////
            /*DESAHABILITA O BOTAO NA HORA E MINUTO DEFINIDOS*/
            if(horas.equals(saida_tec_2)){
                TEC_2_BTN.setEnabled(false);
            }
            if(horas.equals(saida_tec_3)){
                TEC_3_BTN.setEnabled(false);
            }
            ////////////////////////////////////////////////////////////////////
        });
        
        timer.start();
        
        ////////////////////////////////////////////////////////////////////////
        /*DEPOIS DO HORARIO O BOTAO INICIA HABILITADO*/
        if((hora >= hora_chegada_tec_1 && minuto >= minuto_chegada_tec_1)){
            TEC_1_BTN.setEnabled(true);
            TEC_1_BTN.setSelected(false);
            TEC_1_BTN.setBackground(Color.green);
            TEC_1_BTN.setText(""+palavras_separadas_linha_1[0]);
        }
        ////////////////////////////////////////////////////////////////////////
        /*ANTES DO HORARIO O BOTAO INICIA DESABILITADO*/
        if((hora <= hora_chegada_tec_1 && minuto < minuto_chegada_tec_1)){
            TEC_1_BTN.setEnabled(false);
            TEC_1_BTN.setSelected(true);
            TEC_1_BTN.setBackground(Color.red);
            TEC_1_BTN.setText(""+palavras_separadas_linha_1[0]);
        }
        ////////////////////////////////////////////////////////////////////////
        /*ESTES BOTOES INICIAM HABILITADOS*/
        TEC_2_BTN.setSelected(ativar);
        TEC_2_BTN.setBackground(Color.green);
        TEC_2_BTN.setText(""+palavras_separadas_linha_2[0]);
        
        TEC_3_BTN.setSelected(ativar);
        TEC_3_BTN.setBackground(Color.green);
        TEC_3_BTN.setText(""+palavras_separadas_linha_3[0]);
        ////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////
        /*DEPOIS DO HORARIO O BOTAO INICIA DESABILITADO*/
        if((hora >= hora_saida_tec_1 && minuto >= minuto_saida_tec_1)){
            TEC_1_BTN.setEnabled(false);
        }
        if((hora >= hora_saida_tec_2 && minuto >= minuto_saida_tec_2)){
            TEC_2_BTN.setEnabled(false);
        }
        if((hora >= hora_saida_tec_3 && minuto >= minuto_saida_tec_3)){
            TEC_3_BTN.setEnabled(false);
        }
        ////////////////////////////////////////////////////////////////////////
        
    }//GEN-LAST:event_formWindowOpened

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
        BOTAO_ZERAR.setEnabled(desativar);//Ao primeiro clique habilita o botão zerar
        
        vez++;//A cada clique incrementa +1  
        
        ////////////////////////////////////////////////////////////////////////
        /*SE NENHUM BOTAO ESTIVER HABILITADO*/
        if(!TEC_1_BTN.isSelected() && TEC_2_BTN.isSelected() && TEC_3_BTN.isSelected() || 
          !TEC_1_BTN.isEnabled() && !TEC_2_BTN.isEnabled() && !TEC_3_BTN.isEnabled()){
            JOptionPane.showMessageDialog(null,"Habilite pelo menos um Técnico.","Aviso",JOptionPane.WARNING_MESSAGE);
        }
        ////////////////////////////////////////////////////////////////////////
        /*SE NENHUM BOTAO ESTIVER HABILITADO*/
        if(TEC_1_BTN.isSelected() && TEC_2_BTN.isSelected() && TEC_3_BTN.isSelected() || 
          !TEC_1_BTN.isEnabled() && !TEC_2_BTN.isEnabled() && !TEC_3_BTN.isEnabled()){
            JOptionPane.showMessageDialog(null,"Habilite pelo menos um Técnico.","Aviso",JOptionPane.WARNING_MESSAGE);
        }
        ////////////////////////////////////////////////////////////////////////
        /*SE A VEZ FOR DO 1º E O MESMO ESTIVER DESABILITADO*/
        if(vez == 1 && TEC_1_BTN.isSelected() || vez == 1 && !TEC_1_BTN.isEnabled()){
            vez++;
        }
        ////////////////////////////////////////////////////////////////////////
        /*SE A VEZ FOR DO 2º E O MESMO ESTIVER DESABILITADO*/
        if(vez == 2 && TEC_2_BTN.isSelected() || vez == 2 && !TEC_2_BTN.isEnabled()){
            vez++;
        }
        ////////////////////////////////////////////////////////////////////////
        /*SE A VEZ FOR DO 3º E O MESMO ESTIVER DESABILITADO*/
        if(vez == 3 && TEC_3_BTN.isSelected() || vez == 3 && !TEC_3_BTN.isEnabled()){
            vez=1;
        }
        ////////////////////////////////////////////////////////////////////////
        /*SE APENAS O 2º BOTAO ESTIVER HABILITADO*/
        if(TEC_1_BTN.isSelected() && TEC_3_BTN.isSelected()){
            vez=2;
        }
        ////////////////////////////////////////////////////////////////////////
        /*SE A VEZ FOR DO 1º E O MESMO ESTIVER HABILITADO*/
        if(vez == 1 && !TEC_1_BTN.isSelected()){
            
            TEXTO_NOME_DA_VEZ.setText(palavras_separadas_linha_1[0]+" - "+palavras_separadas_linha_1[1]);
            atendimentos_tec_1++;
            TEC_1_BTN.setText(palavras_separadas_linha_1[0]+" - "+atendimentos_tec_1);
            total_de_atendimentos++;
            
        }
        ////////////////////////////////////////////////////////////////////////
        /*SE A VEZ FOR DO 2º E O MESMO ESTIVER HABILITADO*/
        if(vez == 2 && !TEC_2_BTN.isSelected()){
            
            TEXTO_NOME_DA_VEZ.setText(palavras_separadas_linha_2[0]+" - "+palavras_separadas_linha_2[1]);
            atendimentos_tec_2++;
            TEC_2_BTN.setText(palavras_separadas_linha_2[0]+" - "+atendimentos_tec_2);
            total_de_atendimentos++;
            
        }
        ////////////////////////////////////////////////////////////////////////
        /*SE A VEZ FOR DO 3º E O MESMO ESTIVER HABILITADO*/
        if(vez == 3 && !TEC_3_BTN.isSelected()){ 
            
            TEXTO_NOME_DA_VEZ.setText(palavras_separadas_linha_3[0]+" - "+palavras_separadas_linha_3[1]);
            atendimentos_tec_3++;
            TEC_3_BTN.setText(palavras_separadas_linha_3[0]+" - "+atendimentos_tec_3);
            total_de_atendimentos++;
            
            vez = 0;
        }
        ////////////////////////////////////////////////////////////////////////
        /*SE A VEZ FOR DO 3º E O MESMO ESTIVER DESABILITADO*/
        if(vez == 3 && TEC_3_BTN.isSelected() || vez == 3 && !TEC_3_BTN.isEnabled()){
            vez = 0;
        }
        ////////////////////////////////////////////////////////////////////////
        TEXTO_TOTAL.setText("Atendimentos : "+total_de_atendimentos);
        
        Codigos.Arquivo.gravar("Total de atendimentos: "+total_de_atendimentos,
                               palavras_separadas_linha_1[0]+" = "+atendimentos_tec_1,
                               palavras_separadas_linha_2[0]+" = "+atendimentos_tec_2,
                               palavras_separadas_linha_3[0]+" = "+atendimentos_tec_3);
        
    }//GEN-LAST:event_formMouseClicked

    private void BOTAO_ZERARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_ZERARActionPerformed
        // TODO add your handling code here:
        
        Object[] options = { "Sim", "Não" };   
        int opcao = JOptionPane.showOptionDialog(null,"Deseja zerar a contagem ?","Aviso",
        JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);   
  
        if (opcao != 0){
        //JOptionPane.showMessageDialog(null,"");
        }else{
              
            String senha = "";
            int tentativas = 3;//Define o número de tentativas que o usuário terá para acertar a senha.
            
            for(int i=0;i<tentativas;i++)
            {
                if(!senha.equals(password.senha))      
                {
                    
                    senha = JOptionPane.showInputDialog(null,"Password: ","Warning "+(i+1)+"ª tentativa.",JOptionPane.OK_CANCEL_OPTION);
                    
                }    
            }
            if (!senha.equals(password.senha) || senha.equals(null))    
            {
                JOptionPane.showMessageDialog(null,"Senha incorreta ou operação cancelada","Aviso",JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                vez = 0;
                total_de_atendimentos = 0;
                atendimentos_tec_1 = 0;
                atendimentos_tec_2 = 0;
                atendimentos_tec_3 = 0;
                TEXTO_TOTAL.setText("ATENDIMENTOS : ");
                TEXTO_NOME_DA_VEZ.setText("");
                TEC_1_BTN.setText(""+palavras_separadas_linha_1[0]);
                TEC_2_BTN.setText(""+palavras_separadas_linha_2[0]);
                TEC_3_BTN.setText(""+palavras_separadas_linha_3[0]);
                BOTAO_ZERAR.setEnabled(false);
            }
        }
        
    }//GEN-LAST:event_BOTAO_ZERARActionPerformed

    private void TEC_1_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TEC_1_BTNMouseClicked
        // TODO add your handling code here:
        if(TEC_1_BTN.isSelected()){
            TEC_1_BTN.setSelected(true);
            TEC_1_BTN.setBackground(Color.red);
        }else{
            TEC_1_BTN.setSelected(false);
            TEC_1_BTN.setBackground(Color.green);
        }  
    }//GEN-LAST:event_TEC_1_BTNMouseClicked

    private void TEC_2_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TEC_2_BTNMouseClicked
        // TODO add your handling code here:
        if(TEC_2_BTN.isSelected()){
            TEC_2_BTN.setSelected(true);
            TEC_2_BTN.setBackground(Color.red);
        }else{
            TEC_2_BTN.setSelected(false);
            TEC_2_BTN.setBackground(Color.green);
        }
    }//GEN-LAST:event_TEC_2_BTNMouseClicked

    private void TEC_3_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TEC_3_BTNMouseClicked
        // TODO add your handling code here:
        if(TEC_3_BTN.isSelected()){
            TEC_3_BTN.setSelected(true);
            TEC_3_BTN.setBackground(Color.red);
        }else{
            TEC_3_BTN.setSelected(false);
            TEC_3_BTN.setBackground(Color.green);
        }
    }//GEN-LAST:event_TEC_3_BTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTAO_ZERAR;
    private javax.swing.JToggleButton TEC_1_BTN;
    private javax.swing.JToggleButton TEC_2_BTN;
    private javax.swing.JToggleButton TEC_3_BTN;
    private javax.swing.JLabel TEXTO_HORA;
    private javax.swing.JLabel TEXTO_NOME_DA_VEZ;
    private javax.swing.JLabel TEXTO_TOTAL;
    // End of variables declaration//GEN-END:variables
}